### ISSUE TITLE
Create a definitions tools module

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#156]
There are several existing functions that are used to search/traverse the hierarchical dictionaries representing our AaC DSL in the `util.py` module, and there are some additional functions that would be helpful to have, so it's time to create a dedicated module for working with these models/definitions. 

## AC:

- [ ] A new module is created `definition_tools.py`
- [ ] Util.py definition/model related functions are moved to the new module
- [ ] A new function is added that is able to return definitions by name (see notes for an example)
- [ ] Module has at least 85% code coverage.

## NOTES:
Example get by name:

Given the example model
```
model:
  name: aac-gen-gherkin-behaviors
  description: aac-gen-gherkin-behaviors is an Architecture-as-Code plugin that generates Gherkin feature files from model behavior scenarios.
  behavior:
    - name: gen-gherkin-behaviors
      type: command
      description: Generate Gherkin feature files from Arch-as-Code model behavior scenarios.
      input:
        - name: architecture_file
          type: string
          python_type: str
          description: The yaml file containing the data models to generate as Gherkin feature files.
        - name: output_directory
          type: string
          python_type: str
          description: The directory to write the generated Gherkin feature files to.
      acceptance:
        - scenario: Output Gherkin feature files for behavior scenarios in an Architecture model.
          given:
            - The {{gen-gherkin-behaviors.input.architecture_file}} contains a valid architecture.
          when:
            - The aac app is run with the gen-gherkin-behaviors command and a valid architecture file.
          then:
            - Gherkin feature files are written to {{gen-gherkin-behaviors.input.output_directory}}.
```

We would expect:
```python
definition_tools.get_definition_by_name(model, "aac-gen-gherkin-behaviors") # returns a dict of the plugin model
definition_tools.get_definition_by_name(model, "gen-gherkin-behaviors") # returns a dict of the behavior input "gen-gherkin-behaviors"
```
