### ISSUE TITLE
Make Type References validator plugin more flexible

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#275]
Change the Type Reference validation to a Valid Field Reference validation that accepts field names as arguments. Refer to #249 for initial implementation.

Example new validation:
```yaml
schema:
  name: Field
  fields:
    - name: name
      type: string
      description: |
        The name of the field.

        Used to refer to the field, in certain cases.
    - name: type
      type: string
      description: |
        The type of the field.

        Used to constrain the field's values to make it simpler to reason about. Must
        reference an existing definition by name.
    - name: description
      type: string
      description: |
        A description for the field to let users know what it's for and any
        other useful information.
  validation:
    - name: Required fields are present
      arguments:
      - name
      - type
    - name: Type references exist
      arguments:
        - type
```

## Notes:
Type References validator can be found here: https://github.com/jondavid-black/AaC/tree/main/python/src/aac/plugins/validators/defined_references 

The `validation_args` argument is a list of strings that should already contain any arguments defined in the yaml.

Example of the exclusive fields validator using validator arguments https://github.com/jondavid-black/AaC/blob/465dcac15664b9065baba6427cdd51fdbf81e8c3/python/src/aac/plugins/validators/exclusive_fields/_exclusive_fields.py#L25

## AC:
- [x] The `Type References` validator is updated to accept arguments
- [x] The `Type References` validator only validates the fields named via the validation arguments
- [x] Update existing AaC models using the `Type references exist` with one argument entry "type"
