### ISSUE TITLE
Gen Protobuf Filenames should have spaces stripped

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#342]
Gen Protobuf Filenames should have spaces stripped.

Example model that'll expose the issue:
```yaml
schema:
  name: User Request
  description: Example user request for blog post(s)
  fields:
    - name: UserID
      type: int
    - name: Blog Post IDs
      type: int[]
      description: The list of requested blog posts
```
