### ISSUE TITLE
Gen-Design Doc fails to handle type references with periods.

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#380]
When a field name contains a '.' and is referenced in a type field, the `gen-design-doc` command throws an error.
```
gen-design-doc: general_failure

An unrecognized error occurred:/workspace/AaC/python/src/aac/plugins/gen_design_doc/gen_design_doc_impl.py line 48 message: 'dict object' has no attribute 'SubSchema'
```

This can be replicated with this simple yaml example:
```yaml
schema:
  name: Schema1
  fields:
    - name: data
      type: SubSchema.Schema1
---
schema:
  name: SubSchema.Schema1
  fields:
    - name: data
      type: string
```

## AC:
- [ ] Gen design doc can generate design documents with definitions containing '.' in their names.
