### ISSUE TITLE
Validating yaml with malformed ext does not work properly

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#386]
I've been beating my head against the validator for a while now.  All it was providing was a general error and a line reference nowhere close to where the issue was.  It appears the language context is trying to apply the `ext` definition in the model file being validated rather than just validate the contents.

To repeat the issue define a enum incorrectly (in this case using the old `dataExt` rather than `schemaExt`):
```
ext:
  name: addReportToRoot
  type: root
  dataExt:
    add:
      - name: report
        type: Report
```
When you run `aac validate file-with-invalid-aac.yaml` you get the following resopnse:
```
validate: general_failure

An unrecognized error occurred:/workspace/AaC/python/src/aac/cli/builtin_commands/validate/validate_impl.py line 20 message: 'NoneType' object has no attribute 'get'
```
The expected behavior would be a message stating that a defined field in the provided yaml file is incorrect.
