### ISSUE TITLE
Protobuf message should strip spaces from names

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#422]
Protobuf message should strip spaces from names for messages, enums, and fields.

Protobuf style guides for reference:
* [Protobuf enum style guide](https://developers.google.com/protocol-buffers/docs/style#enums)
* [Protobuf message and field style guide](https://developers.google.com/protocol-buffers/docs/style#message_and_field_names)

Recreating the issue:
1. Alter `TimerAlert` in `model/alarm_clock/structures.yaml` to the following:
  a.  `TimerAlert` to `Timer Alert`
  b.  `alarmNoise` to `alarm Noise`
  c.  `AlarmNoise` to `Alarm Noise`
  
```yaml
schema:
  name: Timer Alert
  description: Data structure for timer alerts.
  fields:
    - name: triggeredTime
      type: Timestamp
    - name: alarm Noise
      type: Alarm Noise
```

2. Update `AlarmNoise` to `Alarm Noise` in `model/alarm_clock/structures.yaml` to the following:
  a.  `AlarmNoise` to `Alarm Noise`
```yaml
enum:
  name: Alarm Noise
  description: List of available alarm noises
  values:
    - "Sonic Boom"
    - "Siren"
    - "Klaxon"
    - "Dog Barking"
```

This leads to the following errant output:

Example enum error:
```proto
/* List of available alarm noises */
enum Alarm Noise {
  SONIC BOOM = 1;
  SIREN = 2;
  KLAXON = 3;
  DOG BARKING = 4;
}
```
Example message error:
```proto
/* Data structure for timer alerts. */
message Timer Alert {
  
  Timestamp triggeredTime = 1;
  
  Alarm Noise alarm Noise = 2;
}
```

The expectation is that these names correctly handle spaces and produce correct output like so:

Expected enum output:
```proto
syntax = "proto3"

/* List of available alarm noises */
enum AlarmNoise {
  SONIC_BOOM = 1;
  SIREN = 2;
  KLAXON = 3;
  DOG_BARKING = 4;
}
```

Expected message output:
```proto
/* Data structure for timer alerts. */
message TimerAlert {
  
  Timestamp triggeredTime = 1;
  
  AlarmNoise alarmNoise = 2;
}
```

## AC:
- [x] Schema definition names must have spaces removed and converted to camelCase.
- [x] Schema definition field names must have spaces removed and converted to camelCase.
- [x] Enum definition names must have spaces removed and converted to camelCase.
- [x] Enum values/constants must have spaces replaced with underscores
