### ISSUE TITLE
Specification validation for unique names

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#517]
When importing both a "parent" and a "grandparent" specification where the "parent" also imports the "grandparent", validation results in an invalid error ```Validation finding from 'Unique definition names' of level ERROR```.  It appears to "double validate" on each import resulting in the error.  This can be resolved by knowing about the import of the "grandparent" within the "parent" and omitting the "grandparent" import.

Desired behavior:  do not "double check" for unique names between direct and indirect imports.

I consider this a bug because:
1. The user may not comprehend all the nested imports that may be present.
2. If you reference requirements from multiple spec files, the user should have a reasonable expectation that each spec file should be imported without resulting in an error.

Example:
grandparent.yaml
```yaml
spec:
  name: Grandparent Specification
  description:  A high level set of requirements.
  sections:
    - name: A Great Section
      description: "A set of great high level requirements."
      requirements:
        - id: System_01
          shall: "The system shall be awesome."
        - id: System_02
          shall: "The system shall do cool stuff."
```
parent.yaml
```yaml
import:
  - grandparent.yaml
spec:
  name: Parent Specification
  description:  A refined set of requirements.
  sections:
    - name: A More Detailed Section
      description: "A set of great more detailed requirements."
      requirements:
        - id: Module_01
          shall: "The system shall be super cool."
          parent:
            ids:
              - "System_01"
```
child.yaml
```yaml
import:
  - grandparent.yaml
  - parent.yaml
spec:
  name: Child Specification
  description:  A low level set of requirements.
  sections:
    - name: A Super Detailed Section
      description: "A set of great super detailed requirements."
      requirements:
        - id: Component_01
          shall: "The system shall be totally bodacious."
          parent:
            ids:
              - "System_02"
              - "Module_01"
```

Running ```aac validate child.yaml``` should result in the 'Unique definition names' error although everything is named uniquely.  Removing the import of 'grandparent.yaml' and rerunning ```aac validate child.yaml``` should result in no error.

**Comment by Coffee2Bits** [comment]
Hmm. I'm not seeing any validation failures with these example files. I can think of a few possible causes for that behavior, but I'll need to be able to recreate the behavior to address it. Can you also verify which version of AaC you're using (0.1.5, main)? 

I've created a copy of the example files in a Gitpod snapshot. If you're inclined, you can open a copy of the instance [with this link.](https://gitpod.io#snapshot/ea4dbd46-c151-4dea-bb16-3fe837d8c3dc) Once the instance is up, you can run validate on your example files in the directory `AaC/python/model/test/`. Alternatively, you can checkout the branch `517-demo` and run validate on the files there.

**Comment by jondavid-black** [comment]
Sorry that the above example didn't actually replicate the error.  It took me a bit, but I've got a configuration now that shows the behavior.  It appears that it may have something to do with file paths appearing different but actually referring to the same file.

Example:

./grandparent.yaml
```yaml
spec:
  name: Grandparent Specification
  description:  A high level set of requirements.
  sections:
    - name: A Great Section
      description: "A set of great high level requirements."
      requirements:
        - id: System_01
          shall: "The system shall be awesome."
        - id: System_02
          shall: "The system shall do cool stuff."
```

./system.yaml
```yaml
import:
  - ./parent/module-a.yaml
  - ./otherparent/module-b.yaml
  - ./grandparent.yaml

model:
  name: system
  description: A collection of modules.
  requirements:
    - System_01
    - System_02
  components:
    - name: ModuleA
      type: module-a
    - name: ModuleB
      type: module-b
```

./parent/parent.yaml
```yaml
import:
  - ../grandparent.yaml
  
spec:
  name: Parent Specification
  description:  A refined set of requirements.
  sections:
    - name: A More Detailed Section
      description: "A set of great more detailed requirements."
      requirements:
        - id: Module_01
          shall: "The system shall be super cool."
          parent:
            ids:
              - "System_01"
```

./parent/modlue-a.yaml
```yaml
import:
  - ./parent.yaml
  - ../otherparent/otherparent.yaml
  
model:
  name: module-a
  description: The thing that needs to be amazing.
  requirements:
    - Module_01
    - Other_Module_01
```

./otherparent/otherparent.yaml
```yaml
import:
  - ../grandparent.yaml

spec:
  name: Other Parent Specification
  description:  A refined set of requirements.
  sections:
    - name: Another More Detailed Section
      description: "A set of great more detailed requirements."
      requirements:
        - id: Other_Module_01
          shall: "The system shall be wicked awesome."
          parent:
            ids:
              - "System_01"
```

./otherparent/module-b.yaml
```yaml
import:
  - ./otherparent.yaml
  
model:
  name: module-b
  description: The second thing that needs to be amazing.
  requirements:
    - Other_Module_01
```

To replicate run ```aac validate ./system.yaml``` from the top level directory.

Result (with identifying info removed from paths):
```
Failed to validate:


Validation finding from 'Unique definition names' of level ERROR in .\test\parent\../otherparent/otherparent.yaml. Message:
 Definition 'Other Parent Specification' is defined in:
  .\test\parent\../otherparent/otherparent.yaml at 5:8

Validation finding from 'Unique definition names' of level ERROR in .\test\otherparent\./otherparent.yaml. Message:
 Definition 'Other Parent Specification' is defined in:
  .\test\otherparent\./otherparent.yaml at 5:8

Validation finding from 'Unique definition names' of level ERROR in .\test\./grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\./grandparent.yaml at 2:8
  .\test\parent\../grandparent.yaml at 2:8

Validation finding from 'Unique definition names' of level ERROR in .\test\parent\../grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\./grandparent.yaml at 2:8
  .\test\parent\../grandparent.yaml at 2:8

Validation finding from 'Unique definition names' of level ERROR in .\test\otherparent\../grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\otherparent\../grandparent.yaml at 2:8
  .\test\parent\../grandparent.yaml at 2:8

Validation finding from 'Unique definition names' of level ERROR in .\test\parent\../grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\otherparent\../grandparent.yaml at 2:8
  .\test\parent\../grandparent.yaml at 2:8

Validation finding from 'Unique definition names' of level ERROR in .\test\otherparent\../grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\otherparent\../grandparent.yaml at 2:8
  .\test\./grandparent.yaml at 2:8

Validation finding from 'Unique definition names' of level ERROR in .\test\./grandparent.yaml. Message:
 Definition 'Grandparent Specification' is defined in:
  .\test\otherparent\../grandparent.yaml at 2:8
  .\test\./grandparent.yaml at 2:8
```

My hypothesis:  it's using the file path as part of the uniqueness test, but the absolute path appears different due to the ```../``` traversing the directory structure in the import references.  I haven't looked at the code to see if this hypothesis has any validity.
