### ISSUE TITLE
Validation needs to gracefully handle empty entries

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#572]
Validation needs to gracefully handle empty entries as it currently throws parser errors.

Example:
```yaml
model:
  name: Example
---
---
model:
 name: OtherExample
``` 

Output error:
```yaml
Failed to parse /workspace/AaC/python/model/alarm_clock/alarm_clock.yaml

provided content was not YAML
import:
  - ./structures.yaml
model:
  name: AlarmClock
  description: A simple alarm clock
  components:
    - name: clock
      type: Clock
    - name: timer
      type: ClockTimer
    - name: alarm
      type: ClockAlarm
  behavior:
    - name: setAlarm
      type: request-response
      description: Set the alarm timer
      input:
        - name: targetTime
          type: Timestamp
      acceptance:
        - scenario: setTimer
          when:
            - The user sets the alarm timer
          then:
            - The alarm is triggered when the clock reaches the specified time
---
---
import:
  - ../alarm_clock/structures.yaml
model:
  name: Clock
  description: A simple clock that keeps track of the current time
  behavior:
    - name: getTime
      type: timer
      description: Get the current time
      output:
        - name: currentTime
          type: Timestamp
---
model:
  name: ClockTimer
  description: A simple timer that can be set to a target time.
  state:
    - name: targetTime
      type: Timestamp
      description: The target timestamp indicating when to fire the alarm alert.
  behavior:
    - name: setTime
      type: request-response
      description: Set the target time for the timer
      input:
        - name: targetTime
          type: Timestamp
    - name: triggerTimer
      type: timer
      description: Dispatch the TimerAlert when the current time matches the target time
      input:
        - name: currentTime
          type: Timestamp
      output:
        - name: timerAlert
          type: TimerAlert
---
model:
  name: ClockAlarm
  description: A simple alarm that produces noise.
  behavior:
    - name: triggerAlarm
      type: request-response
      description: Trigger the alarm noise when a TimerAlert is received.
      input:
        - name: timerAlert
          type: TimerAlert
      output:
        - name: alarmNoise
          type: AlarmNoise
```

## Reference
[Source of the invalid YAML error](https://github.com/jondavid-black/AaC/blob/faac161eb652a19c3eacb633c28b232258c68221/python/src/aac/io/parser/_yaml.py#L49C1-L50)

## AC:
- [x] The validator can successfully parse and validate files with empty definitions
